services:

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "10002:6379"
    networks:
      - goorm-network
    volumes:
      - redis-data:/data

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: goorm_exp
      MYSQL_USER: goorm_exp
      MYSQL_PASSWORD: 00000000
    ports:
      - "10001:3306"
    networks:
      - goorm-network
    volumes:
      - goorm-db-volume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 5

  goormexp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: goorm-exp
    container_name: goormexp
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - TZ=Asia/Seoul
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
    ports:
      - "8080:8080"
    networks:
      - goorm-network
    volumes:
      - goorm-application-volume:/application
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone:ro
    depends_on:
      mysql:
        condition: service_healthy

networks:
  goorm-network:
    driver: bridge

volumes:
  goorm-application-volume:
  goorm-db-volume:
  redis-data:
