services:
  goormexp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: goorm-exp
    container_name: goormexp
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - TZ=Asia/Seoul
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
    ports:
      - "8080:8080"
    networks:
      - goorm-network
    volumes:
      - goorm-application-volume:/application
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone:ro

networks:
  goorm-network:
    driver: bridge

volumes:
  goorm-application-volume:
  goorm-db-volume:
